# This Chapter tells you the brief description about the python
# lets begin

print("-----------------------------------------------------------let's do python-----------------------------------------------------------\n")
print("Q1. What is python ?\n")
print("Ans :- Python is a high level object oriented scriptive language that is used develop the website, application software and automation task ")
print("Python was created in the late 1980s\n")
print("Q2. What is script ?\n")
print("Ans :- In terms of programming language A Script is a set of instruction the are executed line by line.\n")
print("Q3. Who develop the python ?\n")
print("Ans :- Guido van Rossum while he was working in netherland\n")
print("Q4. What are the basic uses of python ?\n")
print("Ans :- 1 . Web Development\n       2. Software development\n       3. Data Science\n       4. Automation \n")
print("Q5. What we going to learn ?\n")
print("Ans :- We are going to learn python for AI/ML and for Data science\n")
print("Q6. Feature/property or why we use python?\n")
print("Ans :- 1. Python is easy to learn\n       2. No need to think much about the memory handle tech using pointer, array python will take care of it itself\n       3.open source\n")
print("Q7. How does the name python comes from ?\n")
print("Ans :- while guido van rossum was working on a language and was confuse to give the name to the new language project .\nIncidently the BBC was broadcasting the shows name monty flying circus and the guido van rossum was found of the that shows and the character that he like most was python .\nFinally he decide to give the new name to the language project as python")
print("Q8. How many python IDE available ?\n")
print("Ans :-Pycharm\t\tSpyder\n\t  VS Code\t\tJupiter Notebook\n\t  IDLI\t\t\tVIM\n\t  Emac\nAre some famous IDE to write down the script of the python")
print("Q9. Which IDE you used ?\n")
print("Ans :- We use VS Code.\n")
print("Q10. Consol V/s Display")
print("Ans :- Text base interaction is called consol while visual representation of data is called display")
print("Q11. What are the keyword? And how may keywords in python?")
print("Ans :- Keyword are the reserved word. These word cann't be used for any other purpose. They do have some specific task or purpose\nThere are 35 Keyword in python")
print("Ans :-\n")
print("\t\tFalse\t\tNone\t\tTrue\t\tand\t\tas\t\tassert\t\tasync\t\tawait\t\tbreak\t\tclass\t\tcontinue")
print("\t\tdef\t\tdel\t\telif\t\telse\t\texcept\t\tfinallyt\t\tfor\t\tfrom\t\tglobal")
print("\t\tif\t\timport\t\tin\t\tis\t\tlambda\t\tnonlocal\t\tnot\t\tor\t\tpass")
print("\t\traise\t\treturn\t\ttry\t\twhile\t\twith\t\tyield")
print("Q12. What are control flow keyword in python?")
print("Ans :- The keyword that control the flow of the programme is known as control key word.")
print("like : -\n\t\tif\t\telse\t\telif\t\twhile\t\tfor etc")
print("Q12. What are exception handling in python?")
print("Ans :- The keyword that are used to handle the exception in programme is known as exception handler.")
print("like : -\n\t\ttry\t\tcatch\t\tfinally")
print("Q12. misc?")
print("Ans :- def - define function \nlambda - Create annonyms function\nclass - define class")
print("global - use global variable in fuction\nnonlocal - modifying the variable in an enclosing function")
print("Boolean - True,False\nNone - represent the no value or none")
print("Logical comparision ")
print("logical operator :- and, or , not")
print("Identifires :- is,in")
print("Import module :-  import,as,from ")
print("Resource management :- with - like file handling")
print("del - delete an object")
print("self - represent the instance of the class")
print("property of the below data type in python")
print("\t\t\tlist\t\t\ttuple\t\t\tset\t\t\tdictonary\t\tbyte\t\tbytearray")
print("mutable \tyes\t\t\t\tNo\t\t\t\tyes\t\t\tyes\t\t\t\tno\t\t\tYes")
print("Ordered \tyes\t\t\t\tyes\t\t\t\tyes*/No*\tyes\t\t\t\tyes\t\t\tYes")
print("Duplicate \tyes\t\t\t\tyes\t\t\t\tNo\t\t\tNo\t\t\t\tyes\t\t\tYes")

print("An object that can be called like a function using parentheses ().")


print("*args  =  Store the tuple value in while calling the function ")
print("**kwargs =  stores the dict value while passing through the function calling")
