import pandas as pd

dict1 = {"Name":["Pryanka","Satyajeet","Wishwajeet","Rahul","Amit","Shivesh","Arif","Pryanka"],
"Marks":[90,93,98,90,89,55,56,90],
"Gender":["Female","Male","Male","Male","Male","Male","Male","Female"]}

df = pd.DataFrame(dict1)
print(df)
print("Display the 3 First row of the dataframe")
print(df.head(3))
print("Display the 3 last row of the dataframe")
print(df.tail(3))
print("Display shape of the dataframe")
print(df.shape)
print("Display number of row of the dataframe")
print(df.shape[0])
print("Display number of column of the dataframe")
print(df.shape[1])
print("Display info of the dataframe")
print(df.info())
print("Display is null of the dataframe as per column ")
print(df.isnull().sum(axis=0))            #Default parameter passed in sum function is axis =0 which is column 
print("Display is null of the dataframe as per row ")
print(df.isnull().sum(axis=1))            #Now we pass in sum function is axis = 1 which is row
print("Get all the stastics of the dataframes")
print(df.describe(include="all"))            #Display the statisctis of the mark column only because the describe function display the statistcis of the column contains the numerical values only 
print("Get the unique values for the data fram from the perticular colun")
print(df['Name'].unique())
print("Count of the unique value for the perticular colums")
print(df["Gender"].value_counts())
print("Total Number of sutdent who has score the between 90 to 93")
print(len(df[(df["Marks"] >=90) & (df["Marks"] <= 93)]))
print("Get the total number of student having number between 90 and 93 using between methode")
print(sum(df["Marks"].between(90,93)))
print("Fine out the averge of the marks")
print(sum(df["Marks"])/len(df))
print("Fine out the averge of the marks using mean function")
print(df["Marks"].mean())
print("Print the minimum marks of the students")
print(df["Marks"].min())
print("Print the max marks of the students")
print(df["Marks"].max())

print("Apply function in pandas ")
print("We create a user define function  which take an argument received from left side of the apply function iteratable series ")
def marks(a):
    return a//2
print(df["Marks"].apply(marks))
print(type(df["Marks"]))
print("Attache new colum to the data frame ")
df["Half_Marks"] = df["Marks"].apply(marks)
print(df)
print("Apply Lambda function on datafram")
df["Two times of half"] = df["Half_Marks"].apply(lambda x : x*2)
print(df)
print("Find out the len of each name in our name column")
df["Name length"] = df["Name"].apply(len)
print(df)
print("Drop the colomn from the data fram")
print(df.drop("Half_Marks",axis=1))
print("Original data frame")
print(df)
print("drop multiple column")
print("We need to pass as python list")
df.drop(["Half_Marks","Two times of half","Name length"],axis=1,inplace =True)
print(df)
print("Use map function to map the female to 0 and male to 1")
df["Male_female"] = df["Gender"].map({"Male":1,"Female":0})
print(df)
print("Original Data Frame")
df.drop(["Male_female"],axis=1,inplace =True)
print(df)
print("Arrage data as accoring to the values in marks by ascending order")
df.sort_values(by="Marks",ascending=True,inplace=True)
print(df)
print("Arrage data as accoring to the values in marks by descending order")
df.sort_values(by="Marks",ascending=False,inplace=True)
print(df)
print("Arrage data as accoring to the name by ascending order")
df.sort_values(by="Name",ascending=True,inplace=True)
print(df)
print("Get the marks of the female student only ")
df1  = df[df['Gender'] =="Female"][['Name','Marks']]
print(df1[['Name','Marks']])
# print("Original Data")
# df  = df["Marks","Name"])